### ISSUE TITLE
All edits but 500 are considered deleted

### ISSUE THREAD

**Issue by nemobis** [ricordisamoa/labs#8]
Tried Botcrux or Addbot on it.wiki, got unrealistic results like:

Live edits: 500
Deleted edits: 550.424
Total edits (including deleted): 550.924

**Comment by ricordisamoa** [comment]
I just discovered that this has always been the case with uploads (continuation broken), fixed with 8d1b0ab380550fe05646b23959d29fe0c18bc3c0.
